apiVersion: v1
kind: Namespace
metadata:
  name: zxj
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: jenkins-zh
  name: jenkins-zh
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins-zh
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-zh
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        image: surenpi/jenkins-zh:vPR-43-7
        imagePullPolicy: IfNotPresent
        name: website
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-zh
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-zh
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: jenkins-zh
spec:
  rules:
  - host: preview.jenkins-zh.cn
    http:
      paths:
      - backend:
          serviceName: jenkins-zh
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - {}
