name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: hugo-deploy-gh-pages
        uses: jenkins-zh/hugo-gh-actions@v0.0.2
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
          HUGO_VERSION: "0.53"
          WEBSITE_GIT: "git@github.com:jenkins-zh/jenkins-zh.github.io.git"
          WEBSITE_DIR: "jenkins-zh.github.io"
